name: talk_to_me
description: A sample web application built using AngularDart
dependencies:
  browser: ">=0.8.10"
  angular: ">= 0.9.5 < 0.9.6"
  uuid: ">=0.1.6 <=1.0.0"
dev_dependencies:
  unittest: ">= 0.8.10 <2.0.0"
  dartmocks: ">= 0.5.0"
environment:
  sdk: ">=1.0.0 <2.0.0"